### ISSUE TITLE
Fix links on saltpack.org/implementations

### ISSUE THREAD

**Issue by mlsteele** [keybase/saltpack#3]
The 3 links under the *Go* heading on [https://saltpack.org/implementations](https://saltpack.org/implementations) point to the old github.com/keybase/client/tree/master/go/saltpack locations which are gone.

They should point to the new locations including [https://godoc.org/github.com/keybase/saltpack#pkg-examples](https://godoc.org/github.com/keybase/saltpack#pkg-examples)

**Comment by maxtaco** [comment]
Thanks @mlsteele! @oconnor663 can you take a look?

**Comment by oconnor663** [comment]
Fixed, thanks for pointing that out.
