### ISSUE TITLE
Any way to add a comment?

### ISSUE THREAD

**Issue by underyx** [keybase/saltpack#37]
I publish conference notes (sometimes) in [a public GitHub repo](https://github.com/underyx/conference-notes)

Today I took some notes where the presenter asked me not to make my notes public. To still keep all my notes organized and in one place, I wanted to commit the notes encrypted with my own public key. Since this would look very weird, I wanted to also add an explanatory comment (which I'd do in the PGP `Comment:` field normally) to explain why the contents are encrypted.

I'm having trouble, however, finding a way to do something like this. Is it even possible, or planned?

**Comment by oconnor663** [comment]
It's not possible or planned I'm afraid. I'd recommend either using a separate file in the same folder, or maybe encoding your saltpack string inside another data format that supports comments, like TOML.
