### ISSUE TITLE
Deadlink in README.md

### ISSUE THREAD

**Issue by wilsonehusin** [keybase/saltpack#51]
Bottom of README, there is a link on "spec" which redirects to `/encryption-format` but looks like the new one is supposed to be `/encryption-format-v2`

**Comment by maxtaco** [comment]
cc @oconnor663

**Comment by oconnor663** [comment]
Thanks for catching!

**Comment by wilsonehusin** [comment]
The same dead link exists in the [website](https://saltpack.org)'s index page too.

![image](https://user-images.githubusercontent.com/14004487/36681195-f3a67f2e-1ae5-11e8-84f0-e93ab0210ade.png)

**Comment by oconnor663** [comment]
Another good catch! Fixed.
