### ISSUE TITLE
Key interfaces are too OOP

### ISSUE THREAD

**Issue by gabriel** [keybase/saltpack#8]
SigningPublicKey interface has Verify method:
https://github.com/keybase/saltpack/blob/3f752afeda53a6e28d4875b3aeb29bf0e1ad74d6/key.go#L101

Also SigningSecretKey interface has Sign method.

That's very OOP of it... but maybe not ideal.. Maybe the interface name needs the change and the BasePublicKey becomes PublicKey...

I think the interfacer linter reports on this too.

@oconnor663

**Comment by oconnor663** [comment]
The Verify method is called [here](https://github.com/keybase/saltpack/blob/3f752afeda53a6e28d4875b3aeb29bf0e1ad74d6/verify_stream.go#L114) and [here](https://github.com/keybase/saltpack/blob/3f752afeda53a6e28d4875b3aeb29bf0e1ad74d6/verify.go#L78) I think. Were you worried it wasn't used, or just thinking we should move it around?
